<table>
    <thead>
        <tr>
            <td>Category</td>
            <td>Budget</td>
            <td>Spending</td>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>Make Up</td>
            <td>1,500,000</td>
            <td>0</td>
        </tr>
        <tr>
            <td>Gas</td>
            <td>250,000</td>
            <td>0</td>
        </tr>
        <tr>
            <td>Shopping</td>
            <td>500,000</td>
            <td>0</td>
        </tr>
        <tr>
            <td>Food</td>
            <td>900,000</td>
            <td>0</td>
        </tr>
        <tr>
            <td>Groceries</td>
            <td>900,000</td>
            <td>0</td>
        </tr>
        <tr>
            <td>Phone</td>
            <td>160,000</td>
            <td>0</td>
        </tr>
    </tbody>
</table>